- egorm/component.go
- egorm/container.go
- egorm/init.go
- egorm/instance.go
> 更新gorm的包，alias到gorm

- egorm/init.go
> upgrade ego

- eetcd/registry/component.go
> remove useless code

- egorm/examples/gorm/config.toml
- examples/client/gorm/config.toml
> add config.toml

- eetcd/registry/component.go
> fix logger fieldKey

- ewechat/config.go
- ewechat/container.go
- ewechat/context/context.go
- ewechat/oauth2/oauth.go
- go.mod
> 增加网页版本微信登录

- ekafka/consumerserver/component.go
- ekafka/consumerserver/config.go
- 补充了 `consumerName` 的 tag
- 全部改为使用结构化日志
> fix: 解决 #48 中的问题

- ekafka/README.md
官方文档描述中默认是 FirstOffset ，待确认
https://github.com/segmentio/kafka-go/pull/277/files#diff-32c8fe84ed1fd8985f5d152bfc30b70e66c8281529340a03186812abe16744a7R133
> chore(docs): default startOffset

- ekafka/README.md
- ekafka/consumerserver/component.go
- ekafka/consumerserver/handler.go
- ekafka/examples/consumerserver/main.go
主要改动：
- `EachMessage` -> `OnEachMessage`，并且新增了 Consumer Server 的生命周期 context 参数
- 新增 `OnStart` 方法用来注册纯手动消费的处理回调，满足高级使用场景
> feat: 支持全手动消费模式 & 优化API设计

- egorm/interceptor.go
- emongo/interceptor.go
- eredis/config.go
- eredis/interceptor.go
support gorm trace
support redis trace
support slow log
> support gorm trace

- ek8s/component.go
- ek8s/registry/component.go
- ek8s/watcher_app.go
- ek8s/watcher_endpoints.go
- ek8s/watcher_pod.go
> fix watcher app queue

- ek8s/registry/component.go
> resolver register k8s

- ek8s/go.mod
- ek8s/go.sum
> fix k8s module conflict

- eredis/ecronlock/component.go
- eredis/ecronlock/config.go
- eredis/ecronlock/container.go
- eredis/ecronlock/option.go
支持默认应用名前缀 "ecronlock:{appName}:" 和 WithPrefix Option
> feat(ecronlock): 定时任务锁新增前缀

- eetcd/component.go
- eetcd/config.go
etcd support FailOnNonTempDialError
> etcd support FailOnNonTempDialError

- eetcd/examples/server/config.toml
- eetcd/readme.md
- eetcd/registry/component.go
> fix etcd registry ttl

- eoauth2/README.md
- eoauth2/server/access.go
- eoauth2/server/access_option.go
- eoauth2/server/authorize.go
- eoauth2/server/authorize_option.go
- eoauth2/server/component.go
- eoauth2/server/config.go
- eoauth2/server/container.go
- eoauth2/server/context.go
- eoauth2/server/urivalidate.go
oauth2 refresh token and logger
> oauth2 refresh token

- ejira/configx.go
- ejira/service_issue.go
> feat: add getAllIssueTypes api

- ekafka/README.md
- ekafka/examples/simple_producer/main.go
- ekafka/examples 增加 producer 简单使用示例
- README 添加 Producer 使用说明 和 TOC
> chore(ekafka/docs): add ekafka producer example and docs

- ejira/service_issue.go
> feat: add GetProjectIssueTypes

- eoauth2/server/access.go
- eoauth2/server/config.go
- eoauth2/storage/redisstorage/config.go
- eoauth2/storage/redisstorage/storage.go
- eoauth2/storage/redisstorage/token.go
> 支持单点登录refresh token，增强安全性

- egorm/go.mod
- egorm/go.sum
> upgrade dmgo to v1.8.5

- checkgobuild.sh
- eemqtt/component.go
eemqtt 组件发送qos=0的消息时，会导致线程死锁崩溃
> fix：  PublishMsg when qos = 0 An error occurred

- ekafka/component.go
- ekafka/go.mod
- ekafka/go.sum
kafka-go fixed Merge Request
https://github.com/segmentio/kafka-go/pull/869
reproduce code
```go
package main
import (
"context"
"fmt"
"log"
"time"
"github.com/segmentio/kafka-go"
"github.com/segmentio/kafka-go/sasl/plain"
)
func main() {
ctx := context.Background()
w := &kafka.Writer{
Addr:         kafka.TCP("localhost:9092"),
Topic:        "test-topic",
BatchTimeout: 50 * time.Millisecond,
Transport: &kafka.Transport{
SASL: plain.Mechanism{
Username: "sasl_user",
Password: "sasl_password",
},
},
BatchSize: 1,
Logger: kafka.LoggerFunc(func(format string, args ...interface{}) {
log.Printf("[kafka_go_demo] Kafka writer: "+format, args...)
}),
Async: false,
}
for {
err := w.WriteMessages(ctx, kafka.Message{
Value: []byte("some test message"),
})
if err != nil {
fmt.Printf("kafka write error …
```
> fix: upgrade kafka-go@v0.4.33 fixed produer unexpected EOF error
